const STUDENTS_REQUEST = "STUDENTS_REQUEST";
const STUDENTS_SUCCESS = "STUDENTS_SUCCESS";
const STUDENTS_FAILURE = "STUDENTS_FAILURE";

const STUDENTS_POST = "STUDENTS_POST";
const STUDENTS_GET = "STUDENTS_GET";
const STUDENTS_PATCH = "STUDENTS_PATCH";
const STUDENTS_DELETE = "STUDENTS_DELETE";

export {
  STUDENTS_PATCH,
  STUDENTS_POST,
  STUDENTS_GET,
  STUDENTS_DELETE,
  STUDENTS_FAILURE,
  STUDENTS_SUCCESS,
  STUDENTS_REQUEST
};
